Internal Server Error: /add-dish/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 32, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 415, in add_dish
    dish.save()  # Save the dish instance first
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/files/storage/base.py", line 38, in save
    name = self._save(name, content)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/storages/backends/s3.py", line 565, in _save
    obj.upload_fileobj(content, ExtraArgs=params, Config=self.transfer_config)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/boto3/s3/inject.py", line 764, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/boto3/s3/inject.py", line 675, in upload_fileobj
    return future.result()
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/s3transfer/futures.py", line 111, in result
    return self._coordinator.result()
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/s3transfer/futures.py", line 287, in result
    raise self._exception
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/s3transfer/tasks.py", line 142, in __call__
    return self._execute_main(kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/s3transfer/tasks.py", line 165, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/s3transfer/upload.py", line 796, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/botocore/client.py", line 595, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/botocore/client.py", line 1058, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs
"POST /add-dish/ HTTP/1.1" 500 145
Internal Server Error: /menu/lakshay-chetal/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 518, in public_menu
    Prefetch('dishes',
NameError: name 'Prefetch' is not defined
"GET /menu/lakshay-chetal/ HTTP/1.1" 500 145
Internal Server Error: /menu/lakshay-chetal/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 518, in public_menu
    Prefetch('dishes',
NameError: name 'Prefetch' is not defined
"GET /menu/lakshay-chetal/ HTTP/1.1" 500 145
Internal Server Error: /menu/lakshay-chetal/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 518, in public_menu
    Prefetch('dishes',
NameError: name 'Prefetch' is not defined
"GET /menu/lakshay-chetal/ HTTP/1.1" 500 145
Internal Server Error: /menu/lakshay-chetal/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 518, in public_menu
    Prefetch('dishes',
NameError: name 'Prefetch' is not defined
"GET /menu/lakshay-chetal/ HTTP/1.1" 500 145
Internal Server Error: /menu/lakshay-chetal/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 541, in public_menu
    return render(request, 'menu_management/public_menu_swiggy.html', {
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: menu_management/public_menu_swiggy.html
"GET /menu/lakshay-chetal/ HTTP/1.1" 500 145
Internal Server Error: /menu/lakshay-chetal/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/views.py", line 541, in public_menu
    return render(request, 'menu_management/public_menu_swiggy.html', {
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: menu_management/public_menu_swiggy.html
"GET /menu/lakshay-chetal/ HTTP/1.1" 500 145
Internal Server Error: /add-restaurant/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /add-restaurant/ HTTP/1.1" 500 145
Internal Server Error: /add-restaurant/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /add-restaurant/ HTTP/1.1" 500 145
Internal Server Error: /add-restaurant/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /add-restaurant/ HTTP/1.1" 500 145
Internal Server Error: /super-admin-dashboard/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /super-admin-dashboard/ HTTP/1.1" 500 145
Internal Server Error: /super-admin-dashboard/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /super-admin-dashboard/ HTTP/1.1" 500 145
Internal Server Error: /super-admin-dashboard/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /super-admin-dashboard/ HTTP/1.1" 500 145
Internal Server Error: /super-admin-dashboard/
Traceback (most recent call last):
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/menu_management/decorators.py", line 11, in _wrapped_view
    return redirect('login')
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/lchetal/Downloads/flavar trae/restaurant_project/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /super-admin-dashboard/ HTTP/1.1" 500 145
